import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
  Index,
} from 'typeorm';

@Entity('users')
export class User {
  @PrimaryColumn('uuid')
  id: string; // Generated by us now

  @Column({ unique: true, nullable: true })
  email: string;

  @Column({ unique: true })
  @Index()
  handle: string;

  @Column({ name: 'display_name' })
  @Index() // Useful for search
  displayName: string;

  @Column({ type: 'text', nullable: true })
  bio: string;

  @Column({ name: 'is_protected', default: false })
  isProtected: boolean;

  @Column({ name: 'invites_remaining', default: 3 })
  invitesRemaining: number;

  @Column({ type: 'text', array: true, default: '{}' })
  languages: string[];

  @CreateDateColumn({ name: 'created_at' })
  @Index() // Explicit index for sorting by new users
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;

  @DeleteDateColumn({ name: 'deleted_at' })
  deletedAt: Date;

  @Column({ name: 'follower_count', default: 0 })
  @Index() // Useful for "suggested users" sorting
  followerCount: number;

  @Column({ name: 'following_count', default: 0 })
  followingCount: number;

  @Column({ name: 'quote_received_count', default: 0 })
  quoteReceivedCount: number;

  @Column({ type: 'jsonb', default: {} })
  preferences: Record<string, any>;

  @Column({
    name: 'last_username_change_at',
    type: 'timestamp',
    nullable: true,
  })
  lastUsernameChangeAt: Date | null;
}
